"""Rebuild the realistic-workflow table from preserved remote summaries."""
import csv
import json
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
MODELS = [
    ('qwen3-14b', 'Qwen3-14B'),
    ('qwen3.5-9B-nothinking', 'Qwen3.5-9B (no-thinking)'),
    ('qwen3.5-9B-thinking', 'Qwen3.5-9B (thinking)'),
    ('ministral3-14b', 'Ministral-3-14B-Instruct'),
    ('gpt-oss-20b-low', 'GPT-OSS-20B'),
    ('llama3.1-8b', 'Llama-3.1-8B'),
]
CONDITIONS = ['system-terminal', 'forward-terminal', 'system-natural', 'forward-natural']
with (HERE/'counts.csv').open() as f:
    rows=list(csv.DictReader(f))
cells={(m,c):dict(r) for r in rows for m,name in MODELS if r['model']==name for c in [r['condition']]}
for cell in cells.values():
    for field in ('attack_successes','benign_successes','joint_successes'):cell[field]=int(cell[field])
assert len(cells)==24

def percent(count):
    return str((Decimal(count) * 100 / 54).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP))

rows = []
audit = []
for model, label in MODELS:
    values = []
    for condition in CONDITIONS:
        cell = cells[model, condition]
        values.extend([percent(cell['attack_successes']), percent(cell['benign_successes'])])
        audit.append(dict(model=label, condition=condition, n=54,
                          attack_successes=cell['attack_successes'], benign_successes=cell['benign_successes'],
                          joint_successes=cell['joint_successes'], source_path=cell['source_path'], source_sha256=cell['source_sha256']))
    rows.append(' & '.join([label] + values) + r' \\')

header = r'''% Generated by analysis/realistic-workflows/build_table.py; edit the generator.
\begin{table}[t]
\centering
\setlength{\belowcaptionskip}{4pt}
\caption{Attack success and benign-task completion rates (\%) in concurrent
Workspace and Banking workflows, with 54 executions per model and condition.}
\label{tab:realistic-workflows}
\small
\setlength{\tabcolsep}{5pt}
\renewcommand{\arraystretch}{1.02}
\begin{tabular}{@{}lcccccccc@{}}
\toprule
& \multicolumn{2}{c}{Baseline}
& \multicolumn{2}{c}{+ Guidance}
& \multicolumn{2}{c}{+ Natural feedback}
& \multicolumn{2}{c}{+ Both} \\
\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}\cmidrule(lr){8-9}
\textbf{Model} & Attack & Benign & Attack & Benign & Attack & Benign & Attack & Benign \\
\midrule
'''
footer = r'''
\bottomrule
\end{tabular}
\par\smallskip
{\footnotesize
Domain-specific agents collaborate through role-aligned handoffs, with
legitimate requests and attacker-controlled requests from a compromised entry
running concurrently. Guidance provides task-level handoff instructions;
Natural feedback returns downstream responses; Both enables both mechanisms.\par}
\end{table}
'''
target = ROOT / 'paper/tables/realistic-workflows.tex'
target.write_text(header + '\n'.join(rows) + footer)
print('Validated all 24 workflow cells')
