"""Render the approved token/time table from audited full-execution means."""
import csv
from pathlib import Path

HERE = Path(__file__).resolve().parent
PAPER = HERE.parents[1] / 'paper'
CONDITIONS = ['system-terminal', 'forward-terminal', 'system-empty',
              'system-natural', 'forward-empty', 'forward-natural']
MODELS = [
    ('qwen3-14b', 'Qwen3-14B'),
    ('qwen3.5-9B-nothinking', 'Qwen3.5-9B (no-thinking)'),
    ('qwen3.5-9B-thinking', 'Qwen3.5-9B (thinking)'),
    ('ministral3-14b', 'Ministral-3-14B-Instruct'),
    ('gpt-oss-20b-low', 'GPT-OSS-20B'),
    ('llama3.1-8b', 'Llama-3.1-8B'),
]

with (HERE / 'condition-summary.csv').open(newline='') as stream:
    data = {(r['campaign'], r['condition']): r for r in csv.DictReader(stream)}
assert len(data) == 36
lines = [r'''% Generated by analysis/cost/build_table.py from condition-summary.csv.
\begin{table}[t]
\centering
\setlength{\belowcaptionskip}{4pt}
\caption{Execution costs across six conditions. Mean total tokens
(thousands) and wall-clock time (seconds) are computed from available records.}
\label{tab:execution-cost}
\small
\setlength{\tabcolsep}{3.5pt}
\renewcommand{\arraystretch}{1.05}
\begin{tabular}{@{}llrrrrrr@{}}
\toprule
\textbf{Model} & \textbf{Metric} & \textbf{Baseline} & \textbf{H}
& \textbf{E} & \textbf{N} & \textbf{H + E} & \textbf{H + N} \\
\midrule''']
for index, (campaign, name) in enumerate(MODELS):
    for field, metric, divisor in [('mean_tokens', 'Tokens (k)', 1000),
                                    ('mean_elapsed_seconds', 'Time (s)', 1)]:
        values = [float(data[campaign, condition][field]) / divisor
                  for condition in CONDITIONS]
        label = name if field == 'mean_tokens' else ''
        lines.append(label + ' & ' + metric + ' & ' +
                     ' & '.join(f'{v:.2f}' for v in values) + r' \\')
    if index < len(MODELS) - 1:
        lines.append(r'\addlinespace[3pt]')
lines.append(r'''\bottomrule
\end{tabular}
\par\smallskip
{\footnotesize
H = task-level handoff guidance; E/N = Empty/Natural feedback.
Baseline uses neither task-level guidance nor returned feedback (Terminal);
H alone also uses Terminal feedback. k = 1,000 tokens.\par}
\end{table}''')
output = PAPER / 'tables/execution-cost.tex'
output.write_text('\n'.join(lines) + '\n')
print(output)
