import csv
from pathlib import Path
ROOT=Path(__file__).resolve().parent
PROJECT=ROOT.parents[1]
CONDITIONS=['system-terminal', 'system-empty', 'system-natural', 'forward-terminal', 'forward-empty', 'forward-natural']
MODELS=[('qwen3-14b', 'Qwen3-14B'), ('qwen3.5-9B-nothinking', 'Qwen3.5-9B (no-thinking)'), ('qwen3.5-9B-thinking', 'Qwen3.5-9B (thinking)'), ('ministral3-14b', 'Ministral-3-14B-Instruct'), ('gpt-oss-20b-low', 'GPT-OSS-20B'), ('llama3.1-8b', 'Llama-3.1-8B')]

def render_table(rows):
    lookup={(r["campaign"],r["condition"]):r for r in rows}
    body = []
    for campaign, label in MODELS:
        if (campaign, CONDITIONS[0]) not in lookup:
            continue
        cells = [lookup[campaign, condition] for condition in CONDITIONS]
        values = [r['asr_percent'] for r in cells]
        body.append(label + ' & ' + ' & '.join(values) + r' \\')
    tex = r'''% Generated by analysis/main-asr/build_table.py; edit the generator.
\begin{table}[t]
\centering
\setlength{\belowcaptionskip}{4pt}
\caption{Verified attack success rates (ASR, \%) over 1,890 executions per cell.
Executions ending in errors are counted as unsuccessful attacks.}
\label{tab:main-asr}
\small
\setlength{\tabcolsep}{5pt}
\renewcommand{\arraystretch}{1.02}
\begin{tabular}{@{}r|cccccc@{}}
\toprule
\multicolumn{1}{c|}{\textbf{Model}}
& \multicolumn{1}{c}{$\boldsymbol{-\mathrm{H}\,/\,\mathrm{T}}$}
& \multicolumn{1}{c}{$\boldsymbol{-\mathrm{H}\,/\,\mathrm{E}}$}
& \multicolumn{1}{c}{$\boldsymbol{-\mathrm{H}\,/\,\mathrm{N}}$}
& \multicolumn{1}{c}{$\boldsymbol{+\mathrm{H}\,/\,\mathrm{T}}$}
& \multicolumn{1}{c}{$\boldsymbol{+\mathrm{H}\,/\,\mathrm{E}}$}
& \multicolumn{1}{c}{$\boldsymbol{+\mathrm{H}\,/\,\mathrm{N}}$} \\
\midrule
''' + '\n'.join(body) + r'''
\bottomrule
\end{tabular}
\par\smallskip
{\footnotesize
$+\mathrm{H}/-\mathrm{H}$ = with/without task-level handoff guidance;
$\mathrm{T}/\mathrm{E}/\mathrm{N}$ = Terminal/Empty/Natural downstream feedback.\par}
\end{table}
'''
    (PROJECT / 'paper/tables/main-asr.tex').write_text(tex)


if __name__=="__main__":
    with (ROOT/"source-data.csv").open() as f:render_table(list(csv.DictReader(f)))
